### ISSUE TITLE
Have a error with header files

### ISSUE THREAD

**Issue by mhsily** [heethesh/Balance-Bot#1]
Hello I am student.
I have made separate .cpp files for motors (including encoders), path planning, arm mechanism and one for remaining code. So for main program I have created headers files .h with just declarations of functions and variables.
I have just included header files (.h ) in main program and all the definition  in .cpp.
Error comes if I call function from headers.
See the image attached you will understand everything.
Giude me where the problem is.
![error](https://user-images.githubusercontent.com/63463738/79002615-7521f480-7b6e-11ea-8e5d-19ac7ae6b550.jpg)

**Comment by heethesh** [comment]
There is no `lcd_pin_config` in my source code. You have to fix this yourself.

**Comment by heethesh** [comment]
This does not even look like an issue with this repository.
